# Generated by Django 5.1.3 on 2025-02-26 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='social_login',
            new_name='google_login',
        ),
    ]
