# Generated by Django 5.1.3 on 2025-02-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/agency')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bussiness_logo', models.ImageField(blank=True, null=True, upload_to='business/logo')),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('about_business', models.TextField()),
                ('business_email', models.EmailField(max_length=254, unique=True)),
                ('business_website', models.CharField(blank=True, max_length=100, null=True)),
                ('business_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('target_customer', models.CharField(blank=True, max_length=100, null=True)),
                ('cash_payment', models.BooleanField(default=False)),
                ('online_payment', models.BooleanField(default=False)),
                ('offer_delivery', models.BooleanField(default=False)),
                ('certificate_type', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_image', models.ImageField(upload_to='certificate/image/')),
                ('description', models.TextField()),
                ('business_lat', models.FloatField(blank=True, null=True)),
                ('business_lng', models.FloatField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_count', models.IntegerField(default=0)),
                ('jobs_count', models.IntegerField(default=0)),
                ('rating_count', models.IntegerField(blank=True, default=0, null=True)),
                ('sum_rating', models.FloatField(blank=True, default=0, null=True)),
                ('ratings', models.FloatField(blank=True, default=0, null=True)),
                ('one_star', models.IntegerField(default=0)),
                ('two_star', models.IntegerField(default=0)),
                ('three_star', models.IntegerField(default=0)),
                ('four_star', models.IntegerField(default=0)),
                ('five_star', models.IntegerField(default=0)),
                ('steps', models.IntegerField(default=0)),
                ('profile_completed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InviteMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_email', models.EmailField(max_length=254, unique=True)),
                ('owner_contact', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
