# Generated by Django 5.1.3 on 2025-02-20 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyemploye',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession', to='users.professionprofile'),
        ),
        migrations.AddField(
            model_name='agencyprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_field', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agencygallery',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_gallery', to='agency.agencyprofile'),
        ),
        migrations.AddField(
            model_name='agencyemploye',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_employe', to='agency.agencyprofile'),
        ),
        migrations.AddField(
            model_name='agencyreview',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_review', to='agency.agencyprofile'),
        ),
        migrations.AddField(
            model_name='agencyreview',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_profession', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agencyreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agencyservices',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_service', to='agency.agencyprofile'),
        ),
        migrations.AddField(
            model_name='invitemembers',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_agency', to='agency.agencyprofile'),
        ),
        migrations.AddField(
            model_name='invitemembers',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_members', to='users.professionprofile'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to='agency.agencyprofile'),
        ),
    ]
