# Generated by Django 5.1.3 on 2025-02-24 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='agency.agencyprofile')),
            ],
            options={
                'unique_together': {('agency', 'day_of_week')},
            },
        ),
    ]
