# Generated by Django 5.1.3 on 2025-02-26 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_rename_social_login_sitesettings_google_login'),
        ('agency', '0003_agencyhours'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyservices',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='administration.subcategory'),
        ),
        migrations.AlterField(
            model_name='agencyprofile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_category', to='administration.category'),
        ),
        migrations.AlterField(
            model_name='agencyservices',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_service', to='agency.agencyprofile'),
        ),
    ]
