# Generated by Django 5.1.3 on 2025-02-24 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionprofile',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_profile', to='agency.agencyprofile'),
        ),
        migrations.AddField(
            model_name='professionprofile',
            name='agency_invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_invite', to='agency.agencyprofile'),
        ),
        migrations.AddField(
            model_name='professionprofile',
            name='request_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_agency', to='agency.agencyprofile'),
        ),
    ]
