# Generated by Django 5.1.3 on 2025-02-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionselectedservice',
            old_name='services',
            new_name='service',
        ),
    ]
