# Generated by Django 5.1.3 on 2025-02-27 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_rename_social_login_sitesettings_google_login'),
        ('agency', '0004_agencyservices_service_alter_agencyprofile_category_and_more'),
        ('users', '0008_remove_customuser_otp_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_available', models.BooleanField(default=False)),
                ('is_publish', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gig_category', to='administration.category')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_profession', to='users.professionprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GigFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('gig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gig_faq', to='profession.gig')),
            ],
        ),
        migrations.CreateModel(
            name='GigGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profession/gig/')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profession.gig')),
            ],
        ),
        migrations.CreateModel(
            name='GigLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profession.gig')),
            ],
        ),
        migrations.CreateModel(
            name='GigReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gig_review', to='profession.gig')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profession_review', to='users.professionprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GigSelectedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profession.gig')),
            ],
        ),
        migrations.CreateModel(
            name='GigSelectedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gig_service', to='profession.gig')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_gig', to='administration.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='RequestAttachAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.BooleanField(default=False)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.agencyprofile')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professionprofile')),
            ],
        ),
    ]
